
package ws1c.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetDataForDashBoard", targetNamespace = "http://interrao.ru/UH/DashBoard", wsdlLocation = "http://msk1-t1capp09/is10235_ct_korp_kazna_upfi/ws/GetDataForDashBoard?wsdl")
public class GetDataForDashBoard
    extends Service
{

    private final static URL GETDATAFORDASHBOARD_WSDL_LOCATION;
    private final static WebServiceException GETDATAFORDASHBOARD_EXCEPTION;
    private final static QName GETDATAFORDASHBOARD_QNAME = new QName("http://interrao.ru/UH/DashBoard", "GetDataForDashBoard");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://msk1-t1capp09/is10235_ct_korp_kazna_upfi/ws/GetDataForDashBoard?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETDATAFORDASHBOARD_WSDL_LOCATION = url;
        GETDATAFORDASHBOARD_EXCEPTION = e;
    }

    public GetDataForDashBoard() {
        super(__getWsdlLocation(), GETDATAFORDASHBOARD_QNAME);
    }

    public GetDataForDashBoard(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETDATAFORDASHBOARD_QNAME, features);
    }

    public GetDataForDashBoard(URL wsdlLocation) {
        super(wsdlLocation, GETDATAFORDASHBOARD_QNAME);
    }

    public GetDataForDashBoard(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETDATAFORDASHBOARD_QNAME, features);
    }

    public GetDataForDashBoard(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetDataForDashBoard(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetDataForDashBoardPortType
     */
    @WebEndpoint(name = "GetDataForDashBoardSoap")
    public GetDataForDashBoardPortType getGetDataForDashBoardSoap() {
        return super.getPort(new QName("http://interrao.ru/UH/DashBoard", "GetDataForDashBoardSoap"), GetDataForDashBoardPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetDataForDashBoardPortType
     */
    @WebEndpoint(name = "GetDataForDashBoardSoap")
    public GetDataForDashBoardPortType getGetDataForDashBoardSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://interrao.ru/UH/DashBoard", "GetDataForDashBoardSoap"), GetDataForDashBoardPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETDATAFORDASHBOARD_EXCEPTION!= null) {
            throw GETDATAFORDASHBOARD_EXCEPTION;
        }
        return GETDATAFORDASHBOARD_WSDL_LOCATION;
    }

}
